<?php

function ping_pong_menu() {
    $items ['ping_pong'] = array(
        'title' => 'Ping Pong Problem',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('ping_pong_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $items['result'] = array(
        'title' => 'Ping Pong Solution' ,
        'page callback' => 'ping_pong_solution',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}


function ping_pong_form() {
    $form['count_goal'] = array(
        '#title' => 'Count Goal',
        '#type' => 'textfield',
        '#description' => t('Please enter the number you want to count up to.'),
        '#element_validate' => array('element_validate_integer_positive', 'element_validate_range'),
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go',
    );

    return $form;
}

function element_validate_range($element) {
    if($element['#value'] > 100 || $element['#value'] < 1) {
        form_error($element, t('Number must be less than 100 or greater than 1.'));
    }
}

function ping_pong_form_submit($form, &$form_state) {

    $count_max = $form_state['values']['count_goal'];
    $pingpong_output = array();

    for ($i=1; $i<= $count_max; $i++) {
        if ($i % 3 == 0 && $i % 5 ==0) {
        array_push($pingpong_output, "ping-pong");
        } elseif ($i % 3 == 0) {
            array_push($pingpong_output, "ping");
        } elseif ($i % 5 == 0) {
            array_push($pingpong_output, "pong");
        } else {
            array_push($pingpong_output, $i);
        }

    }

    $_SESSION['ping_pong_output'] = $pingpong_output;
    $form_state['redirect'] = 'result';

}

function ping_pong_solution() {
    $output = '<ul>';
    foreach ($_SESSION['ping_pong_output'] as $value) {
        $output = $output . '<li>' . $value . '</li>';
    }

    $output = $output . '</ul>';
    return "Hooray! $output";
}
